In [33]:
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn import tree
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('titanic.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
df.drop(['PassengerId','Name','Ticket','Cabin','SibSp','Parch','Embarked'],axis='columns',inplace=True)

In [4]:
df.head()

   Survived  Pclass     Sex   Age     Fare
0         0       3    male  22.0   7.2500
1         1       1  female  38.0  71.2833
2         1       3  female  26.0   7.9250
3         1       1  female  35.0  53.1000
4         0       3    male  35.0   8.0500

In [6]:
inputs = df.drop('Survived',axis='columns')
target = df['Survived']

In [16]:
inputs.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [7]:

inputs.Sex = inputs.Sex.map({'male': 1, 'female': 2})

In [8]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())

In [9]:
inputs.head()

   Pclass  Sex   Age     Fare
0       3    1  22.0   7.2500
1       1    2  38.0  71.2833
2       3    2  26.0   7.9250
3       1    2  35.0  53.1000
4       3    1  35.0   8.0500

In [23]:
X_train, X_test, y_train, y_test = train_test_split(inputs, target, test_size=0.2)

In [24]:

model= tree.DecisionTreeClassifier( random_state=42)

In [25]:

model.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [26]:
model.score(X_test, y_test)

0.7932960893854749

In [29]:
model.predict(X_test[:10])

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 1])

In [30]:
X_test

     Pclass  Sex        Age      Fare
656       3    1  29.699118    7.8958
61        1    2  38.000000   80.0000
220       3    1  16.000000    8.0500
222       3    1  51.000000    8.0500
841       2    1  16.000000   10.5000
..      ...  ...        ...       ...
866       2    2  27.000000   13.8583
820       1    2  52.000000   93.5000
721       3    1  17.000000    7.0542
674       2    1  29.699118    0.0000
311       1    2  18.000000  262.3750

[179 rows x 4 columns]

In [31]:
y_test

656    0
61     1
220    1
222    0
841    0
      ..
866    1
820    1
721    0
674    0
311    1
Name: Survived, Length: 179, dtype: int64

In [32]:
import joblib
joblib.dump(model,'decision_tree_classifier.joblib')

['decision_tree_classifier.joblib']

In [28]:
query_df = pd.DataFrame([{
    'Pclass': 3,
    'Sex': 1,
    'Age': 21,
    'Fare': 8.05
}])

prediction = model.predict(query_df)
print(prediction)

[0]